
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.9.0
    container_name: Homepage
    restart: unless-stopped
    env_file: .env # use .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=http"
      - traefik.http.routers.homepage.rule=Host(`homepage.${SERVER}.iot-proxmox.net`)
      - "traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homepage.middlewares=homepage-https-redirect"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - traefik.http.routers.homepage-secure.rule=Host(`homepage.${SERVER}.iot-proxmox.net`)
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.service=homepage"
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
      #- "traefik.http.routers.homepage-secure.middlewares=middlewares-authentik@file" #add this to any container you want to use the Authentik web proxy

networks:
  proxy:
    external: true
